[package]
name = "ssh-copy-id"
version = "1.0.0"
edition = "2021"

[dependencies]
ssh2 = "0.9"
dirs = "5.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
rpassword = "7.2"
which = "5.0"
